### ISSUE TITLE
Integration with NS UI RadListView

### ISSUE THREAD

**Issue by patuku-roy** [TheOriginalJosh/nativescript-collapsing-header#1]
Hi @TheOriginalJosh do you have idea how to integrate with RadListView (NS UI) ? I tried and failed ...

**Comment by JoshDSommer** [comment]
@patuku-roy I know that it's not possible at this time, since it does type checking on the objects being passed to it. I'm not sure if adding NS  UI RadListView compatibility this would be feasible for this plugin though since it would add NS UI RadLisView as a dependency. it may be best addressed in another plugin or in NS UI RadListView its self.

**Comment by patuku-roy** [comment]
@TheOriginalJosh okay I've got your point, but IMHO, I don't think addressing this on NS UI RadListView will be their priority, so instead of using RadListView, I need to find another solution then. Thanks anyway.

**Comment by JoshDSommer** [comment]
@patuku-roy it does work with the current list view, I agree it won't be on their priority. 

I think the best option would to create a new plugin that allows this for the NS UI RadLIstView since it will need the RadListView as a dependency. I would give it a shot but I don't have the free time lately to mess with it.  If you'd like to give it a shot I would suggest forking this repo and adding telerik ui as a dependency then changing all the references of the listView to a RadListView. that would be a good place to start. and may just "work" depending on what api's are exposed for the RadListView...

**Comment by patuku-roy** [comment]
@TheOriginalJosh I don't think so, because when we develop using RadListView as a dependency, later on this plugin going to be tight coupled on RadListView changes, so we better stick with the conventional approach. In other hand, I really need pull to refresh feature on ListView and this is a lack of feature from regular ListView compare with RadListView.

And also I tried to combine with awesome plugin [pull-to-refresh](https://github.com/bradmartin/nativescript-pulltorefresh) from BradMartin but this plugin rejected the pull-to-refresh plugin.

So IMHO I guess the best solution is to avoid this approach for a while until we can find more good solution.
